### PR TITLE
Get rid of ctype

### LINKED ISSUE #173: Get rid of ctype dependency
This library uses ctype_alpha() function in two places.
1. If I'm not wrong this function is locale dependent and I don't see any setlocale() calls. So, would be better to have something that does not depend on locale.
2. If we got rid of this function use the library would not need Ctype extension which is not always installed by default.

I think it should be easy to replace this function with something based on ord() or str[c]spn().

### PR DESCRIPTION
**Pull request by alecpl**
Even if 1-2% slower it does not depend on system locale as ctype functions. Polyfills are even slower.

Fixes #173

### CODE REVIEW

File: src/HTML5/Parser/Tokenizer.php [hunk 1]
```diff
@@ -1188,4 +1188,18 @@ protected function decodeCharacterReference($inAttribute = false)
...
+     *
+     * @param string $input A single-byte string
+     *
+     * @return bool True if it is a letter, False otherwise
+     */
+    protected function is_alpha($input)
+    {
+        $code = ord($input);
+
+        return ($code >= 97 && $code <= 122) || ($code >= 65 && $code <= 90);
```
Comment (stof) [inline src/HTML5/Parser/Tokenizer.php:1203]: to import readability of the code, you might replace the numbers with `\ord('A')` and so on. PHP optimizes such calls (qualified calls to `ord` with a static string as argument) at compile time, so the runtime is the same than putting the number directly. But it makes it easier to understand what the code is about (as it avoids magic numbers)

Comment (goetas) [reply src/HTML5/Parser/Tokenizer.php:1203]: :+1:

**Comment by goetas** [comment]
the suggested improvement can be done later, i'm merging this. I want to prepare a new release soon
